# Generated by Django 3.0.8 on 2020-07-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricRuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.CharField(max_length=36)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
