# Generated by Django 3.0.8 on 2020-07-27 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_historicruns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemodelfordata',
            name='batch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.HistoricRuns'),
        ),
    ]
