# Generated by Django 3.0.8 on 2020-07-27 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_auto_20200727_0817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleModelForExport',
        ),
    ]
